apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-node-port-deploy
  labels:
        app: nginx-node-port-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-node-port-deploy
    spec: 
      containers:
        - name:  nginx-node-port-deploy-container
          image: nginx:alpine
          imagePullPolicy: Always
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port-deploy-service
  labels:
    app: nginx-node-port-deploy
spec:
  selector:
    app: nginx-node-port-deploy
  type: NodePort
  ports:
  - port: 80    
