apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: [YourName]
  namespace: [YourNameSpace]
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: [YourName]
    spec:
      restartPolicy: Always
      containers:
      - name: docker-mvc
        image: [ACR login server]/[image]:[tag]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: docker-mvc    
---
apiVersion: v1
kind: Service
metadata:
  name: [YourName]
  namespace: [YourNameSpace]
spec:
  loadBalancerIP: [ip]
  ports:
  - port: 80
  selector:
    app: [YourName]
  type: LoadBalancer