apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels:
    app: myapp
spec:
  containers:
  - name: pod2-container
    image: ubuntu:14.04
    command: ['bash', '-c', ' exit 0']
    imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure